version: '3.2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: insta:latest
    volumes:
      - type: bind
        source: ../src
        target: /workdir
      - type: bind
        source: ../log
        target: /log
      - type: bind
        source: /Users/ikuta/Downloads/Instagram
        target: /root_data
      - type: bind
        source: ../configs
        target: /configs
    working_dir: /workdir
    command: python main.py
