version: '3.2'

services:
  main:
    build:
      context: .
      dockerfile: Dockerfile
    image: nlp:latest
    volumes:
      - type: bind
        source: ../src
        target: /workdir
    working_dir: /workdir
    command: python main.py --documents_dir ./data --summaries_output_dir ./output --no_cuda true --batch_size 1 --min_length 50 --max_length 100 --beam_size 3 --alpha 0.95 --block_trigram false
